import 'package:travel_ui/models/activity_model.dart';

List<Activity> fes_activities = [
  Activity(
    imageUrl: 'assets/images/Chouara Tannery.jpg',
    name: 'Chouara Tannery',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/University of al-Qarawiyyin (Mosque).jpg',
    name: 'University of al-Qarawiyyin (Mosque)',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/El Glaoui Palace.jpg',
    name: 'El Glaoui Palace',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Marinid Tombs.jpg',
    name: 'Marinid Tombs',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Jardin Jnan Sbil.jpg',
    name: 'Jardin Jnan Sbil',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Al-Attarine Madrasa.jpg',
    name: 'Al-Attarine Madrasa',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Bab Bou Jeloud.jpg',
    name: 'Bab Bou Jeloud',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Bou Inania Madrasa.jpg',
    name: 'Bou Inania Madrasa',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
];

List<Activity> marrakech_activities = [
  Activity(
    imageUrl: 'assets/images/Menara gardens.jpg',
    name: 'Menara gardens',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Day trip to Imlil.jpg',
    name: 'Day trip to Imlil / High Atlas Mountains',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Majorelle Garden.jpg',
    name: 'Majorelle Garden',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Jemaa el-Fnaa & Medina.jpg',
    name: 'Jemaa el-Fnaa & Medina',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
];

List<Activity> chaouen_activities = [
  Activity(
    imageUrl: 'assets/images/Rif Mountains.jpg',
    name: 'Rif Mountains',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Cascades d’Akchour.jpg',
    name: 'Cascades d’Akchour',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Kasbah Museum.jpg',
    name: 'Kasbah Museum',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/Chaouen Rural - Day tours.jpg',
    name: 'Chaouen Rural - Day tours',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
  Activity(
    imageUrl: 'assets/images/The Medina.jpg',
    name: 'The Medina',
    type: 'Tour',
    startTimes: ['09:00'],
    rating: 5,
    price: 0,
  ),
];
